version: 2.1

commands:
  kubectl-setup:
    description: Install kubectl for environment still not have kubectl
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.17/2023-05-11/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
            kubectl version --short --client

  awscli-setup:
    description: Install awscli for environment still not have awscli
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install awscli -y
            aws configure set aws_access_key_id $AWS_ACCESS_KEY
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region us-east-1
            aws --version

jobs:
  build-app:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Build app
          command: |
            cd app
            npm install
            npm run build
      - save_cache:
          paths: [app/node_modules]
          key: app-build

  test-app:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Test app
          command: |
            cd app
            npm install
            npm run test

  scan-app:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Scan app
          command: |
            cd app
            npm install
            npm audit --audit-level=critical

  check-lint-app:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Check lint app
          command: |
            cd app
            npm install
            npm run lint

  build-push-app-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: login docker
          command: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run:
          name: Build docker image
          command: |
            docker build -f docker/Dockerfile . -t namnn10/udacity-capstone:lastest
      - run:
          name: Push docker image
          command: |
            docker push namnn10/udacity-capstone:lastest

  deploy-app:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - awscli-setup
      - kubectl-setup
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: display information of the cluster
          command: |
            aws eks update-kubeconfig --name capstone-cluster
            kubectl cluster-info
            kubectl get all -n kube-system
      - run:
          name: deploy app
          command: |
            kubectl apply -f ./kubernetes/aws-auth-cm.yml
            kubectl apply -f ./kubernetes/deployment.yml      
            kubectl get all
      - run:
          name: smoke test
          command: |
            kubectl port-forward service/uda-app-service 8080:80  > uda-app-forward-port.log 2>&1 &
            echo "Forwarding port to 8080 for run smoke test, wait 30 seconds for port forward"
            sleep 30
            kubectl port-forward service/uda-app-service 8080:80 > uda-app-forward-port.log 2>&1 &
            sleep 10
            http_code=$(curl -LI 127.0.0.1:8080 -o /dev/null -w '%{http_code}\n' -s)
            echo $http_code
            if [[ ${http_code} -eq 200  ]]; then
              echo "Smoke test passed"
              cat uda-app-forward-port.log
              exit 0
            else 
              echo "Smoke test failed"
              cat uda-app-forward-port.log
              exit 1
            fi
            cat uda-app-forward-port.log

workflows:
  default:
    jobs:
      - build-app:
          context: global
      - test-app:
          requires: [build-app]
      - scan-app:
          requires: [build-app]
      - check-lint-app:
          requires: [build-app]
      - build-push-app-image:
          requires: [test-app, scan-app, check-lint-app]
      - deploy-app:
          requires: [build-push-app-image]
